// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "This is a simple task list API",
                "produces": [
                    "application/json"
                ],
                "responses": {}
            }
        },
        "/register": {
            "post": {
                "description": "This is a simple task list API",
                "produces": [
                    "application/json"
                ],
                "responses": {}
            }
        },
        "/todos": {
            "get": {
                "description": "This is a simple task list API",
                "produces": [
                    "application/json"
                ],
                "responses": {}
            },
            "put": {
                "description": "This is a simple task list API",
                "produces": [
                    "application/json"
                ],
                "responses": {}
            },
            "post": {
                "description": "This is a simple task list API",
                "produces": [
                    "application/json"
                ],
                "responses": {}
            }
        },
        "/todos/complete": {
            "put": {
                "description": "This is a simple task list API",
                "produces": [
                    "application/json"
                ],
                "responses": {}
            }
        },
        "/todos/{id}": {
            "get": {
                "description": "This is a simple task list API",
                "produces": [
                    "application/json"
                ],
                "responses": {}
            },
            "put": {
                "description": "This is a simple task list API",
                "produces": [
                    "application/json"
                ],
                "responses": {}
            },
            "delete": {
                "description": "This is a simple task list API",
                "produces": [
                    "application/json"
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
