info:
  contact: {}
paths:
  /login:
    post:
      description: This is a simple task list API
      produces:
      - application/json
      responses: {}
  /register:
    post:
      description: This is a simple task list API
      produces:
      - application/json
      responses: {}
  /todos:
    get:
      description: This is a simple task list API
      produces:
      - application/json
      responses: {}
    post:
      description: This is a simple task list API
      produces:
      - application/json
      responses: {}
    put:
      description: This is a simple task list API
      produces:
      - application/json
      responses: {}
  /todos/{id}:
    delete:
      description: This is a simple task list API
      produces:
      - application/json
      responses: {}
    get:
      description: This is a simple task list API
      produces:
      - application/json
      responses: {}
    put:
      description: This is a simple task list API
      produces:
      - application/json
      responses: {}
  /todos/complete:
    put:
      description: This is a simple task list API
      produces:
      - application/json
      responses: {}
swagger: "2.0"
